using Agate
using Test

include("test_helpers.jl")
include("test_layout_indices.jl")
include("test_library.jl")
include("test_components.jl")
include("test_processes.jl")
include("test_quota_authoring.jl")
include("test_quota_compilation.jl")
include("test_process_compilation.jl")
include("test_nipizd_process_compilation.jl")
include("test_structured_food_web_compilation.jl")
include("test_multistate_compilation.jl")
include("test_direct_model_definition_construction.jl")
include("test_models_construct.jl")
include("test_forwarddiff.jl")
include("test_active_parameters.jl")
include("test_enzyme.jl")
include("test_parameter_directory.jl")
include("test_mass_balance.jl")
include("test_nipizd_reference_trajectory.jl")
include("test_introspection.jl")
include("test_recipe_serialization.jl")
