name = "Agate"
uuid = "41889b7c-c35c-4f16-abd7-94b299d9fd29"
authors = ["Joost de Vries"]
version = "0.0.1"

[deps]
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
