---
title: "Four plankton box model simulation"
format: html
jupyter: julia-1.10
---

# Four plankton box model simulation

In this notebook, we'll create a simple four plankton model using Agate.jl which is then simulated using OceanBioME.jl and Oceananigans.jl.

The model formulation and parameter specification of this example is found in `model.jl` with specific functions such as e.g. `menden_limitation` called from `functions.jl`.

In this model, a single plankton functional type is defined, which can then be specified as predator or prey based on the parameter values. For example, for prey `maximum_grazing_rate` are set to 0, while for predators `maximum_growth_rate` are set to 0.

## Running the model

First we import all packages:

```{julia}
using Agate
using Plots
using Oceananigans.Units

const year = years = 365day

using Oceananigans.Biogeochemistry:
    required_biogeochemical_tracers, required_biogeochemical_auxiliary_fields
```

Then we define the model and initial conditions:

```{julia}
include("model.jl")
model = N2P2ZD()
init_conditions = (N=7.0, Z2=0.05, D=0.0, P1=0.1, P2=0.1, Z1=0.05)
```

Next we run the model simulation. In this case, for 10 years at 10 minute intervals:

```{julia}
timeseries = run_box_model(model, init_conditions; Δt=10minutes, stop_time=10years)
```

Finally, we plot our results:

```{julia}

p1 = plot(timeseries.P1; label="P1", title="Phytoplankton 1")
p2 = plot(timeseries.P2; label="P2", title="Phytoplankton 2")
p3 = plot(timeseries.Z1; label="Z1", title="Zooplankton 1")
p4 = plot(timeseries.Z2; label="Z2", title="Zooplankton 2")
p5 = plot(timeseries.D; label="D", title="Detritus")
p6 = plot(timeseries.N; label="N", title="Nitrogen")

# Arrange plots in a 2x3 layout
p = plot(p1, p2, p3, p4, p5, p6; layout=(2, 3), size=(900, 600))

# Display the plot inline
display(p)
```